package com.cipherbyte.banky.enums;

public enum OccupationEnum {
	AGRICULTURE_AND_ALLIED_ACTIVITIES,
	INDUSTRY_AND_MANUFACTURING,
	INFORMATION_TECHNOLOGY,
	EDUCATION,
	HEALTHCARE,
	BUSINESS_AND_MANAGEMENT,
	GOVERNMENT_AND_PUBLIC_SERVICES,
	CONSTRUCTION_AND_REAL_ESTATE,
	ART_CULTURE_AND_ENTERTAINMENT,
	TRANSPORTATION_AND_LOGISTICS,
	RETAIL_AND_SALES,
	HOSPITALITY_AND_TOURISM,
	FINANCE_AND_BANKING,
	LEGAL_AND_LAW_ENFORCEMENT,
	SCIENCE_AND_RESEARCH,
	SOCIAL_SERVICES,
	SKILLED_TRADES,
	MEDIA_AND_COMMUNICATION,
	AGRICULTURE_RELATED_INDUSTRIES,
	EMERGING_AND_SPECIALIZED_FIELDS
}
