package com.cipherbyte.banky.enums;

public enum ReligionEnum {
	HINDUISM,
	ISLAM,
	CHRISTIANITY,
	SIKHISM,
	BUDDHISM,
	JAINISM,
	ZOROASTRIANISM,
	JUDAISM,
	TRIBAL_AND_INDIGENOUS_RELIGIONS,
	OTHER_RELIGIONS_AND_BELIEFS
}
